name: build

on:
  push:
    branches: [ v0.5.3 ]
  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: windows-latest
    steps:

    - name: build
      run: build

    - name: Artifact x86
      uses: actions/upload-artifact@v3
      with:
        name: artifact_windows_x86
        path: .\x86\*

    - name: Artifact amd64
      uses: actions/upload-artifact@v3
      with:
        name: artifact_windows_amd64
        path: .\amd64\*

    - name: Artifact arm64
      uses: actions/upload-artifact@v3
      with:
        name: artifact_windows_arm64
        path: .\arm64\*
