name: build

on:
  push:
    branches: [ 0.5.3 ]
  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: 0.5.3

    - name: build
      run: cd wireguard-windows && build

    - name: Artifact x86
      uses: actions/upload-artifact@v3
      with:
        name: artifact_windows_x86
        path: .\wireguard-windows\x86\*

    - name: Artifact amd64
      uses: actions/upload-artifact@v3
      with:
        name: artifact_windows_amd64
        path: .\wireguard-windows\amd64\*

    - name: Artifact arm64
      uses: actions/upload-artifact@v3
      with:
        name: artifact_windows_arm64
        path: .\wireguard-windows\arm64\*
